services:
  postgres:
    image: postgres:16
    container_name: todo-postgres
    restart: always
    environment:
      POSTGRES_DB: tododb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      TZ: Asia/Kolkata
      PGTZ: Asia/Kolkata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: